apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer-ui
  namespace: homer
spec:
  rules:
    - host: homer.ghart.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homer
                port:
                  number: 80
