
- name: Install Docker CE (latest) on Ubuntu 24.04 hosts
  hosts: "{{ target_hosts | default('bomato') }}"
  become: yes
  vars:
    docker_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  tasks:
    - name: Install required system packages
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Remove previous Docker packages
      apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
          - containerd
          - runc
        state: absent
        update_cache: yes

    - name: Remove existing Docker repository files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/keyrings/docker.gpg
        - /etc/apt/keyrings/docker.asc

    - name: Update apt cache after removing old Docker sources
      apt:
        update_cache: yes

    - name: Add Docker's official GPG key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Get system architecture
      command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Get Ubuntu codename
      command: lsb_release -cs
      register: ubuntu_codename
      changed_when: false

    - name: Add Docker repository (official, always latest)
      apt_repository:
        repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE and plugins (latest)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Install standalone Docker Compose binary (latest)
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Verify docker-compose installation
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - name: Display docker-compose version
      debug:
        var: compose_version.stdout

    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Docker Hello-World container to verify install
      ansible.builtin.shell: docker run --rm hello-world
      register: docker_test
      changed_when: false

    - name: Display Docker test output
      debug:
        var: docker_test.stdout_lines

    - name: Notify user to add themselves to docker group and reboot
      debug:
        msg: |
          Docker installation complete and verified!
          To use Docker as a non-root user, run:
            sudo usermod -aG docker $USER
          Then log out and back in, or reboot, for group membership to take effect.
