version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.traefikapi.address=:8080
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=darkmoon7621@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Traefik Dashboard & API port
      - "8080:8080"
    restart: unless-stopped
    volumes:
      # Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # acme.json should be created on host instance
      - "./acme.json:/letsencrypt/acme.json"
    labels:
      # Traefik Dashboard HTTP with BasicAuth
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`your_domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=traefikapi"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=garrett:$apr1$ZVKSOp4Y$trWOBhc3kSFRHIXuLiQBU0"

  # user-api-backend:
  #   image: your_user_api_image:latest
  #   labels:
  #     #  HTTPS YOUR APP
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.user-api-backend.rule=Host(`your_domain.com`)"
  #     - "traefik.http.routers.user-api-backend.entrypoints=websecure"
  #     - "traefik.http.routers.user-api-backend.tls=true"
  #     - "traefik.http.routers.user-api-backend.tls.certresolver=myresolver"
  #     - "traefik.http.services.user-api-backend.loadbalancer.server.port=3000" # YOUR APP PORT

