#cloud-config
autoinstall:
  version: 1
  identity:
    username: bomato
    hostname: test
    password: '$6$9/Wy.tMgiKkDLCZJ$77OLbEyEXot0pSZdxpgkCQfUEy.w6a6.vYUWgL7mre5UVtuU/q1FUaaMtqw.a5Sv5TIt9qK6e0J7nJTrEY4h./''
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys: []
    import-keys:
      - https://github.com/garrett928.keys
  packages:
    - vim
    - git
    - fail2ban
    - ufw
    - qemu-guest-agent
    - curl
  updates: all
  shutdown: reboot
  late-commands:
    # Change SSH port to 5188
    - curtin in-target -- sed -i 's/^#Port 22/Port 5188/' /etc/ssh/sshd_config
    - curtin in-target -- sed -i 's/^Port 22/Port 5188/' /etc/ssh/sshd_config
    - curtin in-target -- systemctl restart ssh
    # UFW allow 80, 443, and 5188 (SSH)
    - curtin in-target -- ufw allow 80
    - curtin in-target -- ufw allow 443
    - curtin in-target -- ufw allow 5188
    - curtin in-target -- ufw allow 9080
    # Enable UFW
    - curtin in-target -- ufw --force enable
    # Enable fail2ban
    - curtin in-target -- systemctl enable --now fail2ban
    # Enable qemu-guest-agent
    - curtin in-target -- systemctl enable --now qemu-guest-agent
    # Clone repo to user Documents
    - curtin in-target -- bash -c 'su - bomato -c "git clone https://github.com/garrett928/collective-homelab-stacks ~/Documents/collective-homelab-stacks"'
    # Set execute permission and run setup.sh as the user
    - curtin in-target -- bash -c 'su - bomato -c "chmod +x ~/Documents/collective-homelab-stacks/automation/ubuntu/setup.sh && bash ~/Documents/collective-homelab-stacks/automation/ubuntu/setup.sh"'
