plex:
  image:
    repository: ghcr.io/k8s-at-home/plex
    tag: v1.32.5.7349-8f4248874
  
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 20Gi
    media:
      enabled: true
      type: hostPath
      hostPath: /mnt/truenas/media  # Adjust for your TrueNAS mount
      mountPath: /media
      readOnly: true
    
  nodeSelector:
    kubernetes.io/hostname: b8s-01  # Pin to node with TrueNAS access
    
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: plex.ghart.space
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls
          hosts:
            - plex.ghart.space

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
