apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Tell Traefik to use HTTPS backend
    traefik.ingress.kubernetes.io/service.serversscheme: https
    # Use the middleware in the same namespace
    traefik.ingress.kubernetes.io/router.middlewares: argocd-argocd-server@kubernetescrd
spec:
  rules:
  - host: argocd.ghart.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
  tls:
  - hosts:
    - argocd.ghart.space
    secretName: argocd-server-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: argocd-server
  namespace: argocd  # Same namespace as the ingress
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      X-Forwarded-Host: "argocd.ghart.space"
