---
- name: Ubuntu 24 base setup
  hosts: k8s_nodes
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache and upgrade packages (dist-upgrade)
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
      tags: [update]

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - curl
          - git
          - htop
          - unzip
          - tar
          - net-tools
          - vim
          - qemu-guest-agent
          - wget
        state: present
      tags: [packages]

    - name: Enable and start QEMU Guest Agent
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: true
        state: started
      tags: [qemu]

    - name: Allow SSH traffic on port 22
      ansible.builtin.ufw:
        rule: allow
        port: 22
        proto: tcp
      tags: [firewall]


    - name: Enable and start UFW
      ansible.builtin.ufw:
        state: enabled
      tags: [firewall]

    - name: Ensure UFW service is running
      ansible.builtin.service:
        name: ufw
        state: started
      tags: [firewall]

    - name: Autoremove unnecessary packages
      ansible.builtin.apt:
        autoremove: true
      tags: [cleanup]