# add my ssh keys from github and then disable password loging and root user login

- hosts: "*"
  become: yes
  remote_user: ghart 
  tasks: 
  - name: Set authorized keys taken from github
    ansible.posix.authorized_key:
      user: ghart
      state: present
      key: "{{ lookup('url', 'https://github.com/garrett928.keys', split_lines=False) }}"

  - name: Disable Password Authentication
    lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PasswordAuthentication'
          line="PasswordAuthentication no"
          state=present
          backup=yes
    notify:
      - restart ssh
 
  - name: Disable Root Login
    lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PermitRootLogin'
          line="PermitRootLogin no"
          state=present
          backup=yes
    notify:
      - restart ssh
 
  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted
