- hosts: "*"
  become: yes
  tasks:
    - name: Install the latest version of xcp-guest-utils
      ansible.builtin.yum:
        name: xe-guest-utilities-latest
        state: latest

    - name: Enable and start guest utils service
      ansible.builtin.systemd:
        name: xe-linux-distribution
        enabled: true
        state: started
