kube-prometheus-stack:
  # Install CRDs separately (avoid Argo CD long-annotation issue on CRDs)
  installCRDs: false

  # CRDs are managed outside the chart
  crds:
    enabled: false

  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: truenas-nfs-retain
            resources:
              requests:
                storage: 100Gi
      retention: 90d
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - b8s-01
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - prometheus.ghart.space
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.ghart.space

  grafana:
    persistence:
      enabled: false
      storageClassName: longhorn
      size: 2Gi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - b8s-01
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - grafana.ghart.space
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.ghart.space

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            resources:
              requests:
                storage: 2Gi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - b8s-01
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - alertmanager.ghart.space
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.ghart.space
  prometheusOperator:
    admissionWebhooks:
      # Disable admission webhook jobs and RBAC to avoid hook conflicts
      enabled: false
      patch:
        enabled: true
