- hosts: localhost
  connection: local
  tasks: 
    - name: Enable Dark Mode
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"

    - name: Add minimize button
      community.general.dconf:
        key: /org/gnome/desktop/wm/preferences/button-layout
        value: "'close,minimize,maximize:'"

