apiVersion: v1
kind: Service
metadata:
  name: linkstack-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: linkstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkstack
  template:
    metadata:
      labels:
        app: linkstack
    spec:
      containers:
      - name: linkstack
        image: ghcr.io/linkstackorg/linkstack
        ports:
        - containerPort: 80
