version: "3.8"

services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      HTTP_SERVER_NAME: 'ghart.space'

    volumes:
      - 'linkstack_data:/htdocs'
    ports:
      - '80:80'
    restart: always

volumes:
  linkstack_data:
