# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert
#     kompose.version: 1.34.0 (cbf2835db)
#   labels:
#     io.kompose.service: linkstack
#   name: linkstack
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: linkstack
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert
#         kompose.version: 1.34.0 (cbf2835db)
#       labels:
#         io.kompose.service: linkstack
#     spec:
#       containers:
#           image: linkstackorg/linkstack:latest
#           name: linkstack
#           ports:
#             - containerPort: 80
#               protocol: TCP
#           volumeMounts:
#             - mountPath: /htdocs
#               name: linkstack-data
#       hostname: linkstack
#       restartPolicy: Always
#       volumes:
#         - name: linkstack-data
#           persistentVolumeClaim:
#             claimName: linkstack-data
