apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-storage-pv
spec:
  capacity:
    storage: 20Ti
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.ghart.space
    path: /mnt/tank/media/data
  mountOptions:
    - nfsvers=4.0
    - hard
    - intr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  volumeName: media-storage-pv
  storageClassName: nfs
