volumes:
  uptime-kuma-data:
    driver: local
services:
  uptime-kuma:
    image: glouislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
   