volumes:
  uptime-kuma-data:
    driver: local
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    # ports:
    #   - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - uptime-kuma-internal
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.ghart.space`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-network"

networks:
  uptime-kuma-internal:
    internal: true
    name: uptime-kuma-internal
  traefik-network:
    external: true
    name: traefik-network
