---
# Test PVC and Pod for Democratic CSI
# Based on: https://wazaari.dev/blog/truenas-talos-democratic-csi
#
# Deploy: kubectl apply -f test-pvc-pod.yaml
# Cleanup: kubectl delete -f test-pvc-pod.yaml
#
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: democratic-csi-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod
  namespace: democratic-csi-test
  labels:
    app: storage-test
spec:
  containers:
    - name: test-container
      image: busybox:1.36
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: test-volume
          mountPath: /data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
  restartPolicy: Never
