democratic-csi:
  # CSI Driver Configuration
  csiDriver:
    name: "org.democratic-csi.nfs"

  # Driver Configuration for TrueNAS SCALE with NFS
  driver:
    config:
      driver: freenas-api-nfs
      instance_id:
      httpConnection:
        protocol: https
        host: truenas.ghart.space
        port: 443
        allowInsecure: true
        # API key will be patched post-deployment via kubectl
        apiKey: "1-ihxj7UK0FwOiQZejvIeuvlrjUAEFn7nlypsYeBRhdQOqjSTMUuDBkYwaVGnyYVe5"
      zfs:
        datasetParentName: tank/k8s-pvs
        detachedSnapshotsDatasetParentName: tank/k8s-pvs-snapshots
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0755"
        datasetPermissionsUser: 4000
        datasetPermissionsGroup: 4000
      nfs:
        shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
        shareHost: truenas.ghart.space
        shareAlldirs: false
        shareAllowedHosts: []
        shareAllowedNetworks: []
        shareMaprootUser: root
        shareMaprootGroup: root
        shareMapallUser: ""
        shareMapallGroup: ""

  # Controller (provisioner) configuration
  controller:
    enabled: true
    strategy: deployment
    externalProvisioner:
      extraArgs:
        - --leader-election=true
        - --node-deployment=true
        - --feature-gates=Topology=true
        - --strict-topology=true
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true
      extraArgs:
        - --leader-election=true
        - --node-deployment=true

  # Node configuration
  node:
    hostPID: true
    # Required for privileged operations
    driverRegistrar:
      enabled: true

  # Storage Classes
  storageClasses:
    - name: truenas-nfs
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
        - noatime
        - nfsvers=4

  # Volume Snapshot Classes
  volumeSnapshotClasses:
    - name: truenas-nfs
      deletionPolicy: Delete
      parameters:
        detachedSnapshots: "true"
