democratic-csi:
  # CSI Driver Configuration
  csiDriver:
    name: "org.democratic-csi.nfs"

  # Use existing secret for driver configuration
  driver:
    config:
      driver: freenas-api-nfs
    existingConfigSecret: truenas-csi-driver-config

  # Controller (provisioner) configuration
  controller:
    enabled: true
    strategy: deployment
    externalProvisioner:
      extraArgs:
        - --leader-election=true
        - --node-deployment=true
        - --feature-gates=Topology=true
        - --strict-topology=true
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true
      extraArgs:
        - --leader-election=true
        - --node-deployment=true

  # Node configuration
  node:
    hostPID: true
    # Required for privileged operations
    driverRegistrar:
      enabled: true

  # Storage Classes
  storageClasses:
    - name: truenas-nfs
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
        - noatime
        - nfsvers=4

  # Volume Snapshot Classes
  volumeSnapshotClasses:
    - name: truenas-nfs
      deletionPolicy: Delete
      parameters:
        detachedSnapshots: "true"
