democratic-csi:
  namespaceOverride: democratic-csi

  csiDriver:
    name: "org.democratic-csi.nfs"
    fsGroupPolicy: File

  driver:
    existingConfigSecret: truenas-nfs-driver-config
    config:
      driver: freenas-api-nfs

  controller:
    driver:
      image:
        tag: next

  storageClasses:
    - name: truenas-nfs
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
        - noatime
        - nfsvers=3
        - nolock

  volumeSnapshotClasses:
    - name: truenas-nfs
      deletionPolicy: Delete
      parameters:
        detachedSnapshots: "true"
