apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: monitoring-kube-prometheus-admission
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /rules
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: monitoring-kube-prometheus-admission
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /subjects
    - group: rbac.authorization.k8s.io
      kind: Role
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /rules
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /subjects
    - group: ""
      kind: ServiceAccount
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/snapshot-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-nfs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/democratic-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: democratic-csi-nfs-driver-config
      namespace: democratic-csi
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: application-apps
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/garrett928/collective-homelab-stacks.git
#     targetRevision: HEAD
#     path: kubernetes/applications
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc
