apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Force=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /rules
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /subjects
    - group: rbac.authorization.k8s.io
      kind: Role
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /rules
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: monitoring-kube-prometheus-admission
      namespace: monitoring
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /subjects
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks.git
    targetRevision: HEAD
    path: kubernetes/applications
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
