apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-spotify
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/garrett928/collective-homelab-stacks
    targetRevision: main
    path: kubernetes/applications/your_spotify
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
