apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-conf
  namespace: media
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
