version: "3"

volumes:
  zookeeper-data:
  zookeeper-logs:

networks:
  kafka-network:
    name: kafka-network
    driver: host

services:
  kafka-jmx:
    image: confluentinc/cp-kafka:7.4.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-jmx:29092,PLAINTEXT_HOST://localhost:9092' 
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT' 
      KAFKA_PROCESS_ROLES: 'broker,controller' 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-jmx:29093' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-jmx:29092,CONTROLLER://kafka-jmx:29093,PLAINTEXT_HOST://0.0.0.0:9092' 
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT' 
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER' 
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' 
      