version: '2.4'
services:
  xcp-dell:
    container_name: xcp-dell
    image: ghcr.io/mikedombo/xen-exporter:latest
    environment:
      - XEN_HOST=10.0.0.105
      - XEN_USER=root
      - XEN_SSL_VERIFY=false
      - XEN_PASSWORD=$XEN_PASSWORD
    networks:
      - "monitoring-network"
    # env_file:
      # - stack.env # Defined by portainer. Will need to comment out if run locally
    
networks:
  monitoring-network:
    name: monitoring-network
    external: true
