version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - dashy-data:/app/public
      # - ./dashy.yml:/app/public/config.yml
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - treafik-network
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.rule=Host(`dashy.ghart.space`)"
      - "traefik.http.routers.dashy.entrypoints=websecure"
      - "traefik.http.services.dashy.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.routers.dashy.tls.certresolver=leresolver"
      - "traefik.docker.network=treafik-network"
volumes:
  dashy-data:

networks:
  treafik-network:
    external: true
    name: treafik-network
