version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - dashy-data:/app/public
      # - ./dashy.yml:/app/public/config.yml
    # ports:
    #   - 4000:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Frontend
      # - "traefik.enable=true"
      # - "traefik.http.routers.dashy.rule=Host(`dashy.ghart.space`)"
      # - "traefik.http.routers.dashy.entrypoints=websecure"
      # - "traefik.http.services.dashy.loadbalancer.server.port=8080"
      # - "traefik.http.routers.dashy.service=dashy"
      # - "traefik.http.routers.dashy.tls.certresolver=leresolver"
        - "traefik.enable=true"
        - "traefik.http.services.dashy.loadbalancer.server.port=80"
        - "traefik.http.routers.dashy.entrypoints=https"
        - "traefik.http.routers.dashy.rule=Host(`dashy.ghart.space`)"
        - "traefik.http.routers.dashy.service=dashy"
        - "traefik.http.services.dashy.loadbalancer.server.port=8080"
volumes:
  dashy-data:
