services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    # ports:
    #   - 8086:8086
    # env_file:
    #     - ./.env
    environment:
        # INFLUXDB_META_DIR: /var/lib/influxdb/meta

        INFLUXDB_DATA_DIR: /var/lib/influxdb/data
        INFLUXDB_DATA_WAL_DIR: /var/lib/influxdb/data
        # INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
        # INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
        # INFLUXDB_DATA_SERIES_ID_SET_CACHE_SIZE: 100
        
        # INFLUXDB_HTTP_BIND_ADDRES: :${INFLUXDB_PORT}
        # INFLUXDB_HTTP_ENABLED: "true"
        # INFLUXDB_HTTP_AUTH_ENABLED: "true"

    networks:
        - influxdb-internal
        - traefik-network
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.influx.rule=Host(`influxdb.ghart.space`)"
        - "traefik.http.routers.influx.entrypoints=websecure"
        - "traefik.http.services.influx.loadbalancer.server.port=8086"
        - "traefik.http.routers.influx.service=influx"
        - "traefik.http.routers.influx.tls.certresolver=leresolver"
        - "traefik.docker.network=traefik-network"

volumes:
  influxdb-data:
  influxdb-config:

networks:
  influxdb-internal:
    internal: true
    name: influxdb-internal
  traefik-network:
    external: true
    name: traefik-network
