services:
  influxdb:
    container_name: $INFLUXDB_CONTAINER
    image: influxdb:2.7.5
    volumes:
        - type: volume
          source: influxdb-data
          target: /var/lib/influxdb

        - type: bind
          source: ./influxdb/docker-entrypoint-initdb.d
          target: /docker-entrypoint-initdb.d
          read_only: true
    env_file:
        - ./.env
    environment:
        INFLUXDB_META_DIR: /var/lib/influxdb/meta

        INFLUXDB_DATA_DIR: /var/lib/influxdb/data
        INFLUXDB_DATA_WAL_DIR: /var/lib/influxdb/data
        INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
        INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
        INFLUXDB_DATA_SERIES_ID_SET_CACHE_SIZE: 100
        
        INFLUXDB_HTTP_BIND_ADDRES: :${INFLUXDB_PORT}
        INFLUXDB_HTTP_ENABLED: "true"
        INFLUXDB_HTTP_AUTH_ENABLED: "true"

    networks:
        - monitoring-network
        - treafik-network
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.influx.rule=Host(`influxdb.ghart.space`)"
        - "traefik.http.routers.influx.entrypoints=websecure"
        - "traefik.http.services.influx.loadbalancer.server.port=3000"
        - "traefik.http.routers.influx.service=influx"
        - "traefik.http.routers.influx.tls.certresolver=leresolver"
        - "traefik.docker.network=treafik-network"

volumes:
  influxdb-data:

networks:
  monitoring-network:
    external: true
    name: monitoring-network
  treafik-network:
    external: true
    name: treafik-network
